### ISSUE TITLE
list of possible title getters for TitleReadExtractor

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#123]
Atm the `TitleReadExtractor` got one possible getter for the title: `getTitle()` if there would be a list of those possible getters in the config. That extractor would be able to check for more of them like `getMyTitle()`, `getMyVerySpecialTitle()`, ...

**Comment by dbu** [comment]
okay if we close this one?

**Comment by ElectricMaxxx** [comment]
:+1:
