### ISSUE TITLE
BurgovKeyValueBundle doesn't show any field in sandbox

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/SeoBundle#205]
See http://cmf.liip.ch/en/admin/sandbox/main/demoseocontent/create

The sandbox is enabling the BurgovKeyValueBundle, but it doesn't show any field. I don't know if this is a problem specific for the sandbox or a general bug in the SeoBundle/BurgovKeyValueBundle.

**Comment by dbu** [comment]
hm, that might be a bug with sonata 2.3 or a behaviour change in burgov. it used to show an add button in this case. or it could be that the javascript is not loaded anymore.

**Comment by ElectricMaxxx** [comment]
mh ... just open an issue on burgov...-bundle?

**Comment by ConneXNL** [comment]
I have the same problem with the Menu bundle when you add the attributes etc.

I fixed this locally for me by applying the following:
https://github.com/robhunt3r/KeyValueFormBundle/commit/1a57b344f016041172c6a5c070423b953d9878aa

However, I am not sure who is responsible to make the necessary changes. But if this is a requirement something should  be added to:

http://symfony.com/doc/master/cmf/bundles/menu/sonata_admin.html

**Comment by dbu** [comment]
could that be this problem: https://github.com/symfony-cmf/symfony-cmf-docs/pull/674

if so, we should update the sandbox to handle that. the strange thing is that i definitely remember it working at some point. maybe sonata changed something?

**Comment by dbu** [comment]
it indeed was missing configuration. see https://github.com/symfony-cmf/cmf-sandbox/pull/298
