### ISSUE TITLE
SeoBundle breaks sonata admin with simple admin definition on an ORM entity?

### ISSUE THREAD

**Issue by EdwardIII** [symfony-cmf/SeoBundle#211]
I'm trying to make one of my ORM models SeoAware and then edit it in the auto generated admin but can't get past this error.

When I try a URL like this generated by sonata admin:

    /admin/mymodel/London/edit

I get this exception:

    You should close previous group with end() before adding new tab

My Admin class:

https://gist.github.com/EdwardIII/8d9f36b482db9be5ae47

Full stack trace here: 

https://gist.github.com/EdwardIII/b966c21962203d5bd48e

SEO bundle version here:

https://gist.github.com/EdwardIII/9a581edcb15542deee55

Full composer.lock here:

https://gist.github.com/EdwardIII/1f9b2c7d453c83cc5cb2

**Comment by ElectricMaxxx** [comment]
@EdwardIII as you found the issue on sonata-admin - close?

**Comment by dbu** [comment]
even when just using $formMapper->add(), an implicit group is started that must be explicitly closed. see https://github.com/sonata-project/SonataAdminBundle/issues/2721
