### ISSUE TITLE
Have a way to determine sitemap change frequency individually

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/SeoBundle#212]
The PHPCR SitemapUrlInformationProvider always assigns the default changefreq on the sitemap. Instead we could have an extractor for that information (e.g. based on class or an interface that lets tune this by document, or whatever custom logic).

See https://github.com/symfony-cmf/SeoBundle/pull/196/files#r24715055

**Comment by ElectricMaxxx** [comment]
You would like to add that to the 1.2 mile stone (if we have one)?

**Comment by dbu** [comment]
the 1.2 milestone is long overdue - we never released seo 1.2 
when you are on the issue list, you have a "milestone" thing above to go to manage and create milestones. 1.2 already exists, you can select it to the right under the labels.

i am -1 on blocking the 1.2 release with this. if you find time to do it, fine, but otherwise we should aim for a release as soon as possible.

**Comment by ElectricMaxxx** [comment]
the last sentence was the answer i wanted :-)

**Comment by WouterJ** [comment]
We could also have sort of UrlInformation enhancers (can be integrated together with #221). These can then behave like sort of guessers for some values.

**Comment by dbu** [comment]
i would not see this as required for the 1.2 release. i don't see problems adding this in a loter later release only.
