### ISSUE TITLE
Change year in Licence information

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#214]
From (c) 2011-2014 to (c) 2015

**Comment by dbu** [comment]
wait, i think for stuff that already exists, you want to keep the starting year. although in the case of this bundle, the correct thing probably is 2014-2015

**Comment by ElectricMaxxx** [comment]
You meain new classes from new commit got (c) 2015 the other (c) 2014 -2015 ?

**Comment by dbu** [comment]
exactly

**Comment by WouterJ** [comment]
Strictly speaken, the year noted in the copyright is a range in which the file was changed. When a file was added in 2014 and never changed, its copyright should always be `(c) 2014`. When a file was first released in 2014 and after that edited in 2016, the copyright in 2016 should be `(c) 2014-2016`.

**Comment by dbu** [comment]
fixed in #220
