### ISSUE TITLE
Extract Sitemap to an own bundle

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#222]
Based on the discussions on #221 and #212 and the PR's following the introducion of the sitemap behavior i would suggest to extract its code and behavior to an bundle called `CmfSitemapBundle`. The functionality is decoupled from the Seo functionality at all and will be extended by the issues mentioned above. 

So should we do it?

**Comment by dantleech** [comment]
I think that makes sense .. +1

**Comment by dbu** [comment]
hm. if it is possible to disable the rest of the SEO stuff, then what would it hurt to have them in the same bundle? if we separate them, we add overhead and need to duplicate things like the extractor mechanism. and no, having a CmfExtractor library seems not the way to go to me. i think we are in a dilemma between clear responsibility and too many bundles. then again, CmfSitemapBundle with no dependency on sonata sounds very clear what it is about.

what are the overlaps we have? extract description and title? maybe we can make that an optional dependency with the option to supply your own code. or could we make the SitemapBundle *depend* on the SeoBundle for these features?

**Comment by ElectricMaxxx** [comment]
@dbu  we need to write own sitemap extractors/enhancers/guessers i think. We should couple both kind of extractors.

**Comment by dbu** [comment]
just had this idea of looking into packagist: https://packagist.org/search/?q=sitemap-bundle

there is like 10 sitemap bundles. some even build on doctrine. maybe we can just leverage that? a pitty for all the work already invested, but we should seriously look at those and think if we can simply write a phpcr-odm integration for one of those.

**Comment by WouterJ** [comment]
There aren't much sitemap bundles that are decoupled out there. Many have requirements on core bundles from their systems, some are way beyond the sitemap scope, most of them require only XML format.

I don't think we can use one of them (please note that we had done some research before the PR started on this topic).

I also don't believe we should make it into a seperate bundle, it's all part of the SEO topic. Yeah, they are decoupled, but if we make this bundle able to disable/enable each seperate feature, I think it's better to keep them in one repository.

**Comment by ElectricMaxxx** [comment]
I will let the vote open until the evening, and start to implement #221 and #212  then either in a new bundle or here. 
votes atm:
:+1: 2x (me too)
:-1: 1x
use an other bundle (no option before): 1x

btw: is there no chance to da a good poll in github?

**Comment by dbu** [comment]
@ElectricMaxxx tried http://poll.gitrun.com/ but looks rather pointless to me.

i think we should first try to find a more-or-less consensus among the core contributors. voting leaves a minority that lost the vote.

@WouterJ sorry, now that you say that i think i remember that we discussed this before. so at this point i would be -1 on splitting as well. rather keep it simple and eventually try to extract one SitemapBundle to rule them all. but that should then not be cmf specific, probably not even symfony specific, but a library for sitemaps and a bundle to integrate into symfony.

**Comment by ElectricMaxxx** [comment]
as we are 2:2 atm i would follow the advise of @dbu and @WouterJ. So we will keep sitemap inside this bundle and i will start to implement the ideas of #221 and #212.

**Comment by dantleech** [comment]
And my vote shouldn't count for much anyway as I sadly don't know enough about this bundle yet.

**Comment by dbu** [comment]
while i agree that there are a lot of extra cool things we can do, i want to push for a release soon. the sitemap is covering about the common 80% already. lets try to collect all issues (like @ElectricMaxxx already started in #225) and check for each if it will be possible without BC breaks or if we need to tweak something before going stable. then we can release and follow up with a next release in 2 months. i will create a sitemap tag and a milestone for the next release so we can organize this a bit.

**Comment by lsmith77** [comment]
I also agree that maybe it makes more sense to run with the 80% solution for now .. depending on how things go we can extract things into a separate Bundle as part of a 2.0 release.

**Comment by WouterJ** [comment]
I don't understand why we should rush now, instead of following the normal release plan.

**Comment by lsmith77** [comment]
oh this isn't necessarily about releasing a minor SeoBundle release before doing the CMF 1.3 release. its more about taking more controlled steps forward. now obviously if the key contributors to this Bundle think that the "80%" solution is useless to them .. then we maybe need to take bigger steps .. but I am hesitant to try and build the super duper sitemap solution before we have gained some experience with a simpler approach.

**Comment by ElectricMaxxx** [comment]
So we have implemented and finalized(#225) the sitemap feature , so what about that discussion?

**Comment by dbu** [comment]
looking at the code, i think the value of what could be extracted is
limited: the provider itself, and the interfaces. on bundle level, there
are the DI tag and the controller.
all the guessers and the loader and voter integrate with something else
from the cmf, mostly the seo bundle.

if we think that is enough to make it worth, we could split it out. but
in the end i think the 2 tasks (metadata extraction and building
sitemaps) are related enough to justify keeping them together.

or where would you draw the line?

- publish workflow is CmfCoreBundle
- phpcr loader is the doctrine bundle
- url guesser is CmfRoutingBundle

each is a very small bit and having a CmfSitemapBundle that depends on
those bundles just for this small bit seems not great.

the alternative could be optional dependencies for those, or even an
optional dependency for the CmfSeoBundle. then again, some people think
optional dependencies are evil.

i am really quite unsure. when i think about using the sitemap in one of
our projects that is not cmf based, it would indeed make kind of sense
(but then again we will want the seo metadata system there as well so we
will need the CmfSeoBundle anyways)

what do others think?

**Comment by ElectricMaxxx** [comment]
implemented it inside SeoBundle.
