### ISSUE TITLE
Add annotation in SeoAwareTrait

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/SeoBundle#229]
Currently the $seoMetaData is missing annotation:
   /**
     * @var SeoMetadata
     *
     * @PHPCRODM\Child
     */

 which makes the trait unable to be used when using annotations for your mapping.

Other bundles like https://github.com/Atlantic18/DoctrineExtensions/tree/master/lib/Gedmo/Blameable/Traits seem to have a separate trait for each driver.

If this is intended, then please close this and look at:
https://github.com/symfony-cmf/symfony-cmf-docs/issues/669

**Comment by dbu** [comment]
we use xml mappings to avoid this issue. but aparently xml/yml mapping does not work with traits. so what you need to do is map that field in your document. so we should update the documentation accordingly, and also the phpdoc of the trait.

adding an annotation directly to the trait would indeed limit this to phpcr-odm. another option could be to extend the trait in each storage specific namespace, repeat the field and add an annotation, as these are copied along with the trait inclusion - but for people using xml / yml mapping, this would again be confusing. so i tend towards the documentation solution.

@ElectricMaxxx how do you think about this?

**Comment by WouterJ** [comment]
I also think we can't change anything in the code and have to document this limitation

**Comment by ConneXNL** [comment]
Recently I've been playing with traits and it seems you can mix xml/annotation traits. However, using annotated traits seems like a blessing if you stick with annotiations for your documents.

You simple use the trait and you are done configuring anything. I made about 5-6 traits for common phpcr use cases (like TranslatableTrait, PublishableTrait etc.)

I think we should add these and call them:
SeoAwarePhpcrTrait etc.

**Comment by ElectricMaxxx** [comment]
Doesn't We have a SeoAwareTrait somewhere?

**Comment by dbu** [comment]
the reason annotations work is that traits in php really work like copy-paste. but if you use xml / yml mapping, the annotation of the trait will not be seen. so all in all i fear we invite more confusion than we gain. well, we might do the trait with annotation and update the doc that when using xml / yml you need to do something, but with annotations there is no need to do anything. @WouterJ do you see a problem with that ? i guess its a bit more convenient for the users.

**Comment by dbu** [comment]
@WouterJ do you have input for this one? its more a question of how its the least error prone and confusing.

**Comment by ElectricMaxxx** [comment]
So what would be the thing to implement? Btw: wouldn't we loose the PHP 5.3 support when using traits?

**Comment by WouterJ** [comment]
@ElectricMaxxx as long as we don't require to use the Trait, we don't loose 5.3 support.

I'm not too fond of the idea, but I think we should add the annotations to the trait (due to limitations of Doctrine mapping).
