### ISSUE TITLE
SitemapUrlInformationProvider does not set lastModification

### ISSUE THREAD

**Issue by WillBBP** [symfony-cmf/SeoBundle#235]
As the title says. I'll be doing a pull request for this within the hour.

**Comment by ElectricMaxxx** [comment]
Please be aware of the currently Open PR. ( the Long one, i am mobile atm)

**Comment by WillBBP** [comment]
Ah, it looks like my three lines could go in Sitemap/Guesser->guessValues after line 75 something like this?

        if (method_exists($object, 'getLastModification')) {
            $urlInformation->setLastModification($object>getLastModification());
        }

**Comment by dbu** [comment]
see #236
