### ISSUE TITLE
is SitemapElementInterface still used?

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/SeoBundle#240]
seems to be essentially unused, none of the new sitemap infrastructure is using it.

https://github.com/symfony-cmf/SeoBundle/blob/master/SitemapElementInterface.php

we might add the sitemap name to the method and create a voter for it, if we think we should have that, e.g. for an admin flag "show in sitemap".

**Comment by ElectricMaxxx** [comment]
I think this interface isn't used anymore. The voters decide whether an element is included or not.

**Comment by dbu** [comment]
currently there is one voter, the publish workflow voter. it could make sense to have documents expose a flag whether they want to be on the sitemap. alternatively it could be a method to get the list of sitemaps the document is to be included. but that would need a way to say "all" and "nothing".

**Comment by ElectricMaxxx** [comment]
@dbu so you would implement a simple voter to check that interface and the value of the flag?

**Comment by dbu** [comment]
yes, would make sense with the new architecture i think. and be pretty
trivial, but a valid use case. the dev can then either expose a flag to
the editors, or have some simple logic on a model class to decide.
