### ISSUE TITLE
default templates for xml and html

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/SeoBundle#241]
we provide Resources/views/Sitemap/index.xml.twig and html.twig. but they are not used by default, i think. should we change the defaults to register them, so they are used with every configuration?

**Comment by ElectricMaxxx** [comment]
as i started implementing, i used them and i wanted to let the user overreide them by the normal smyfony template overriding. I don't rember what, bu you found an issue doing so and suggest to put it into the configuraion.

**Comment by dbu** [comment]
with multiple sitemaps, we want to be able to configure different
templates for different configurations.

but my point here is that the default ones should be in the
configuration by default.

**Comment by ElectricMaxxx** [comment]
I now ... I understand. Forgot that.

**Comment by ElectricMaxxx** [comment]
Just a little tweak in the Extension Class with a check in the Tests. If my Football Club plays well tonight i will do it afterwards, tomorrow Morning in train else.
