### ISSUE TITLE
Exception in Admin use the ErrorHandling for the Frontend

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#250]
IS:
When producing an exception in the Sonata Admin Backend the new `SuggestionProviderController` is called  and tries to serve good matches for errors with http status code 404. And the Twig Error handler uses our template to show the errors. That causes problems with parameters, which arn't set, and we loose information the normal template serves.

SHOULD:
The `SuggestionProviderController` should get an exclusion list (pattern) for urls, that it does not have to work on. We can't override the main twig-Template, too. So we should create and use an own one, when the `SuggestionProviderController` really has to work.

**Comment by dbu** [comment]
now only documentation for this is missing, and maybe setup in the sandbox
