### ISSUE TITLE
Don't persist seoMetadata on Sonata Admin update

### ISSUE THREAD

**Issue by xmon** [symfony-cmf/SeoBundle#275]
Hi,

I'm trying to integrate **SeoBundle 1.1.2** in my project with **Symfony 2.7.9**. and **SonataAdminBundle 2.3.7.**
I use **Doctrine ORM**, I have implemented in my Entity correctly seoMetaData object.

When I create a new record, the information in the fields of seoMetaData, saved correctly, but when editing this record, the values of these fields are **not saved to the database in the update**.

Do you have any idea what could be the problem?

Thank you so much for everything.

**Comment by dbu** [comment]
hi @xmon hm, this is difficult to debug without further details. i gather you don't see any error page, right? did you look into the symfony log files? did you check the symfony debug toolbar to see whether a query is run or the update is not attempted at all? what happens if you use a phpunit test to change an SeoMetadata entity and then flush? do you map the seo metadata directly on your entity, or do you use a one to one relation?

**Comment by xmon** [comment]
@dbu Thank you very much for such a quick response.

Indeed, I have not provided information to an answer that solves my problem, first of all, I wanted to throw it if he had already been documented in any way before.

OK, no error is displayed, the message is that it has saved.

I've looked at the log of Symfony and there been no error.

No query is performed with seoMetaData update.

**On INSERT:**
The Request POST Parameters
```
[
  publicado => 1, 
  categoria => 1, 
  titulo => title 6, 
  imagen => 219, 
  texto => [
    textoFormatter => richhtml, 
    rawTexto => <p>Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor lectus nibh. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Proin eget tortor risus. Quisque velit nisi, pretium ut lacinia in, elementum id enim.</p>

  ], 
  seoMetadata => [
    title => seo_metadata title, 
    originalUrl => , 
    metaDescription => seo_metadata metaDescription, 
    metaKeywords => seo_metadata, metakeywords, 
    extraProperties => [
      0 => [
        key => extraproperty-one, 
        value => value-one
      ]
    ]
  ], 
  _token => GnXvHqL2Sg0UyDxPfmvpvR_UN2Ns4TJ2VxTn1yvKGZU
]
```
The Query:
```SQL
INSERT INTO BlogItems (titulo, texto, textoFormatter, rawTexto, publicado, seoMetadata, createdAt, updatedAt, slug, imagen_id, categoria_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```

**On Update.**
The Request POST Parameters
```
[
  publicado => 1, 
  categoria => 1, 
  titulo => title 6 mod, 
  imagen => 219, 
  texto => [
    textoFormatter => richhtml, 
    rawTexto => <p>mod&nbsp;Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor lectus nibh. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Proin eget tortor risus. Quisque velit nisi, pretium ut lacinia in, elementum id enim.</p>

  ], 
  seoMetadata => [
    title => seo_metadata title mod, 
    originalUrl => , 
    metaDescription => seo_metadata metaDescription mod, 
    metaKeywords => seo_metadata, metakeywords mod, 
    extraProperties => [
      0 => [
        key => extraproperty-one, 
        value => value-one mod
      ]
    ]
  ], 
  _token => wUr3RITCo7lvWMf0IZifuGaQS6DSQYHeECwo83_GUAE
]
```

The query:
```SQL
UPDATE BlogItems SET titulo = 'title 6 mod', texto = '<p>mod&nbsp;Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor lectus nibh. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Proin eget tortor risus. Quisque velit nisi, pretium ut lacinia in, elementum id enim.</p>', rawTexto = '<p>mod&nbsp;Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor lectus nibh. Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Proin eget tortor risus. Quisque velit nisi, pretium ut lacinia in, elementum id enim.</p>', publicado = 1, updatedAt = '2016-02-16 01:06:36', slug = 'title-6-mod' WHERE id = 7
```



Here are my settings and my code:

_app/config.yml_
```YAML
cmf_seo:
    sonata_admin_extension:
        enabled: true
                
sonata_doctrine_orm_admin:
    templates:
        form: [ SonataDoctrineORMAdminBundle::form_admin_fields.html.twig ]
```

I map the seo metadata directly on my entity.
_src/AppBundle/Entity/BlogItems.php_
```PHP
namespace AppBundle\Entity;

use Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * BlogItems
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Entity\BlogItemsRepository")
 */
class BlogItems implements SeoAwareInterface
{
    //......

    /**
     * @ORM\Column(type="object")
     */
    protected $seoMetadata;

    /**
     * {@inheritdoc}
     */
    public function getSeoMetadata()
    {
        return $this->seoMetadata;
    }
    /**
     * {@inheritdoc}
     */
    public function setSeoMetadata($metadata)
    {
        $this->seoMetadata = $metadata;
        return $this;
    }
}
```

_src/AppBundle/Admin/BlogItemsAdmin.php_
```PHP
namespace AppBundle\Admin;

//......

class BlogItemsAdmin extends Admin {

    //......

    protected function configureFormFields(FormMapper $formMapper) {

        //......
        $formMapper
                ->with('SEO', array('class' => 'col-md-3'))
                ->add('seoMetadata', 'seo_metadata')
                ->end()
        ;
    }

    //......

}

```

thanks a lot.

**Comment by dbu** [comment]
sorry, not so fast this time... this seems strange, a bit like doctrine orm would not work correctly. can you try to write PHP code that programmatically updates the seo metadata and then flushes doctrine to see if that works? if it does, there might be something with sonata admin and the doctrine ["object"](http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/types.html#object) type mapping. 
if i understand things correctly, your SeoMetadata model would not need a doctrine mapping. SeoBundle provides one in Resources/config/doctrine-model/SeoMetadata.orm.xml . just to be on the safe side, can you try setting `persistence: enabled:` to false in the configuration of cmf_seo? maybe that mapping confuses doctrine?

i am not sure if the issue is related to this bundle at all or a general doctrine orm vs sonata issue. are you using the latest versions of those two? if you define your own dummy model class does it work then, or does it never work?

**Comment by xmon** [comment]
@dbu thanks again.

these are my installed versions:

- doctrine/annotations                     v1.2.7                                                                        
- doctrine/cache                           v1.5.4            
- doctrine/collections                     v1.3.0                                                            
- doctrine/common                          v2.5.3                                                           
- doctrine/dbal                            v2.4.4                                                              
- doctrine/doctrine-bundle                 v1.5.2                                                                 
- doctrine/doctrine-cache-bundle           v1.0.1                                                               
- doctrine/inflector                       v1.1.0                         
- doctrine/lexer                           v1.0.1       
- doctrine/orm                             v2.4.8 
- sonata-project/admin-bundle              2.3.7          
- sonata-project/block-bundle              2.2.13       
- sonata-project/cache                     1.0.7        
- sonata-project/classification-bundle     2.2.1            
- sonata-project/core-bundle               2.3.10        
- sonata-project/doctrine-extensions       1.0.2          
- sonata-project/doctrine-orm-admin-bundle 2.3.3  
- sonata-project/easy-extends-bundle       2.1.9        
- sonata-project/exporter                  1.4.1     
- sonata-project/formatter-bundle          2.3.3     
- sonata-project/google-authenticator      1.0.2    
- sonata-project/intl-bundle               2.2.3      
- sonata-project/media-bundle              2.3.3       
- sonata-project/notification-bundle       2.3.0      
- sonata-project/seo-bundle                1.1.10    

I think that all versions are required by symfony-cmf/SeoBundle.

I tryied with:
```yml
cmf_seo:
    sonata_admin_extension:
        enabled: true
    persistence: 
        orm:
            enabled: false
```
and
```yml
cmf_seo:
    sonata_admin_extension:
        enabled: true
    persistence: 
        phpcr:
            enabled: false
```

with the same result, at update, the changes are not saved on seoMetaData 


Coding PHP in Admin Class, **src/AppBundle/Admin/BlogItemsAdmin.php**

```php

namespace AppBundle\Admin;

//......
use Symfony\Cmf\Bundle\SeoBundle\Model\SeoMetadata;
//......

class BlogItemsAdmin extends Admin {

    //......
    public function preUpdate($blogitem) {
        
        dump($blogitem); // Dump ONE

        $seoMetadataTest = new SeoMetadata();
        $seoMetadataTest
            ->setTitle('Seo Title')
            ->setMetaDescription('Seo Description')
            ->setMetaKeywords('Seo, Keys')
            ->setOriginalUrl('/test')
            ->setExtraProperties(array('og:title' => 'Extra title'))
            ->setExtraNames(array('robots' => 'index, follow'))
            ->setExtraHttp(array('content-type' => 'text/html'))
        ;
        
        dump($blogitem->getSeoMetadata()); // Dump TWO
        dump($seoMetadataTest);  // Dump THREE

        $blogitem->setSeoMetadata($seoMetadataTest);
        dump($blogitem); // Dump FOUR
    }
    
}
```

Yeah :v: , save SeoMetadata...

this are dumps results:
**Dump ONE**
```ObjDump
BlogItems {#1797 ▼
  -id: 2
  -titulo: "titulo 1ss"
  -texto: """
    <p>Proin eget tortor risus. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.</p>\n
    \n
    <p>Vivamus suscipit tortor eget felis porttitor volutpat. Vivamus suscipit tortor eget felis porttitor volutpat. Pellentesque in ipsum id orci porta dapibus.</p>\n
    \n
    <p>Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Nulla porttitor accumsan tincidunt. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.</p>
    """
  -textoFormatter: "richhtml"
  -rawTexto: """
    <p>Proin eget tortor risus. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.</p>\r\n
    \r\n
    <p>Vivamus suscipit tortor eget felis porttitor volutpat. Vivamus suscipit tortor eget felis porttitor volutpat. Pellentesque in ipsum id orci porta dapibus.</p>\r\n
    \r\n
    <p>Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Nulla porttitor accumsan tincidunt. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.</p>
    """
  -imagen: Media {#1856 ▶}
  #categoria: BlogCategorias {#1835 ▶}
  -tags: PersistentCollection {#1216 ▶}
  -productos: PersistentCollection {#2010 ▶}
  -publicado: 1
  #seoMetadata: SeoMetadata {#1793 ▶}
  #createdAt: DateTime {#1794 ▶}
  #updatedAt: DateTime {#1795 ▶}
  #slug: "titulo-1ss"
}
```

**Dump TWO**
```ObjDump
SeoMetadata {#1793 ▼
  -id: null
  -locale: null
  -originalUrl: "mod/"
  -metaDescription: "mod metaDescription Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec sollicitudin molestie malesuada. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada. Pellentesque in ipsum id orci porta dapibus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus."
  -metaKeywords: "mod, metaKeywords, asdfasdf,asdfasdfsad,badbb"
  -title: "el titulo mod"
  -extraProperties: array:1 [▼
    "extraProperties1mod" => "aamod"
  ]
  -extraNames: []
  -extraHttp: []
}
```

**Dump THREE**
```ObjDump
SeoMetadata {#2538 ▼
  -id: null
  -locale: null
  -originalUrl: "/test"
  -metaDescription: "Seo Description"
  -metaKeywords: "Seo, Keys"
  -title: "Seo Title"
  -extraProperties: array:1 [▼
    "og:title" => "Extra title"
  ]
  -extraNames: array:1 [▼
    "robots" => "index, follow"
  ]
  -extraHttp: array:1 [▼
    "content-type" => "text/html"
  ]
}
```

**Dump FOUR**
```ObjDump
BlogItems {#1797 ▼
  -id: 2
  -titulo: "titulo 1ss"
  -texto: """
    <p>Proin eget tortor risus. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.</p>\n
    \n
    <p>Vivamus suscipit tortor eget felis porttitor volutpat. Vivamus suscipit tortor eget felis porttitor volutpat. Pellentesque in ipsum id orci porta dapibus.</p>\n
    \n
    <p>Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Nulla porttitor accumsan tincidunt. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.</p>
    """
  -textoFormatter: "richhtml"
  -rawTexto: """
    <p>Proin eget tortor risus. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.</p>\r\n
    \r\n
    <p>Vivamus suscipit tortor eget felis porttitor volutpat. Vivamus suscipit tortor eget felis porttitor volutpat. Pellentesque in ipsum id orci porta dapibus.</p>\r\n
    \r\n
    <p>Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Nulla porttitor accumsan tincidunt. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.</p>
    """
  -imagen: Media {#1856 ▶}
  #categoria: BlogCategorias {#1835 ▶}
  -tags: PersistentCollection {#1216 ▶}
  -productos: PersistentCollection {#2010 ▶}
  -publicado: 1
  #seoMetadata: SeoMetadata {#2538 ▶}
  #createdAt: DateTime {#1794 ▶}
  #updatedAt: DateTime {#1795 ▶}
  #slug: "titulo-1ss"
}
```

If I try in  **src/AppBundle/Admin/BlogItemsAdmin.php**

```php

namespace AppBundle\Admin;

//......
use Symfony\Cmf\Bundle\SeoBundle\Model\SeoMetadata;
//......

class BlogItemsAdmin extends Admin {

    //......
    public function preUpdate($blogitem) {
        
        $blogitem->setSeoMetadata($blogitem->getSeoMetadata());
    }
    
}
```

it doesn't work :cry: 

any idea with these testing?

thanks again

**Comment by dbu** [comment]
sorry, i am not very familiar with doctrine orm. i wonder if this is an issue of anything the seo bundle does, or if its something with how you nest objects in doctrine. maybe you can try to isolate the issue with a very small and simple object - if you can reproduce the problem with that, ask the doctrine orm problem for help. if that works, maybe you can find the difference to what we do in the seo bundle that could cause the issue?

**Comment by WouterJ** [comment]
Thanks for your report and help to debug this issue @xmon!

This is not a bug in the CmfSeoBundle or SonataAdminBundle, but rather the way Doctrine ORM works with objects. You can see [this stackoverflow answer](http://stackoverflow.com/a/15488230/1149495) for some detailed information. In short, Doctrine doesn't discover changes when you edit properties of an object by reference.

As the Symfony forms handles objects (in this case the `SeoMetadata` instance) by reference by default, doctrine won't know anything has changed. In order to fix this, force Symfony forms to use the setter + getter explicitly:

```php
$formMapper
    ->with('SEO', array('class' => 'col-md-3'))
        ->add('seoMetadata', 'seo_metadata', array('by_reference' => false))
    ->end()
;
```

This solved the problem in my test application, so I think it should solve it in your case as well. However, if you still can't make it work, just leave a comment and we'll reopen this issue.

**Comment by ElectricMaxxx** [comment]
@WouterJ should we add a Testcase as a Kind of a documentation? Even when it is a global issue.

**Comment by WouterJ** [comment]
@ElectricMaxxx doctrine should document this on their side imo, it's not your job to document doctrine's behaviour.

**Comment by xmon** [comment]
Thanks a lot @WouterJ

**Comment by dbu** [comment]
hm, but our [admin extension](https://github.com/symfony-cmf/SeoBundle/blob/master/Admin/Extension/SeoContentAdminExtension.php#L49) adds this to the form without properly disabling by_reference. do we need to detect the doctrine flavour and accordingly set this option?

**Comment by dbu** [comment]
also, we could mention the by_reference in http://symfony.com/doc/master/cmf/bundles/seo/seo_aware.html#form-type as its likely to hit people there. i don't think that would be duplicating the doctrine documentation.

**Comment by WouterJ** [comment]
Hmm, what about defaulting to `by_reference => false` in the form options of the SeoMetadataType?

**Comment by dbu** [comment]
i guess this only works with orm, i don't think phpcr knows about this, right? or is this only a form thing and has nothing to do with doctrine?

**Comment by WouterJ** [comment]
By reference is a form thing:
```php
// by_reference = true (default)
$object->getSeoMetadata()->setTitle($newTitle);

// by_reference = false
$m = $object->getSeoMetadata();
$m->setTitle($newTitle);
$object->setSeoMetadata($m);
```

I don't think disabling by reference will cause any troubles for non-ORM implementations like PHPCR. And the `SeoAwareInterface` requires both the setter and getter.
